### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by nickstaroba** [afzaalace/unsplash#1]
Getting this error when trying to download all images:

C:\Un2>unsplash
C:\Users\Nick\AppData\Roaming\npm\node_modules\unsplash\lib\index.js:151
                downloadImages(imagesToDownloadWithId)
                ^
RangeError: Maximum call stack size exceeded
    at C:\Users\Nick\AppData\Roaming\npm\node_modules\unsplash\lib\index.js:151:17
    at C:\Users\Nick\AppData\Roaming\npm\node_modules\unsplash\node_modules\async\lib\async.js:254:17
    at C:\Users\Nick\AppData\Roaming\npm\node_modules\unsplash\node_modules\async\lib\async.js:157:25
    at C:\Users\Nick\AppData\Roaming\npm\node_modules\unsplash\node_modules\async\lib\async.js:251:21
    at C:\Users\Nick\AppData\Roaming\npm\node_modules\unsplash\lib\index.js:149:21
    at C:\Users\Nick\AppData\Roaming\npm\node_modules\unsplash\node_modules\async\lib\async.js:249:17
    at iterate (C:\Users\Nick\AppData\Roaming\npm\node_modules\unsplash\node_modules\async\lib\async.js:149:13)
    at C:\Users\Nick\AppData\Roaming\npm\node_modules\unsplash\node_modules\async\lib\async.js:160:25
    at C:\Users\Nick\AppData\Roaming\npm\node_modules\unsplash\node_modules\async\lib\async.js:251:21
    at C:\Users\Nick\AppData\Roaming\npm\node_modules\unsplash\lib\index.js:149:21

C:\Un2>

**Comment by afzaalace** [comment]
@nickstaroba Could you confirm if the updated version is working on your version of Windows?

    npm install git+https://github.com/afzaalace/unsplash -g

This will install the latest code from GitHub. You'll require [Git](www.git-scm.com) installed for this to work.

**Comment by nickstaroba** [comment]
Sort of working. It'll download a small number of images and then just stop.

After a number of reattempts I got this error:

      throw er; // Unhandled stream error in pipe.
            ^
Error: EPERM, open 'C:\unsplash2\berries.jpg.jpg'
    at Error (native)
