### ISSUE TITLE
Fresh install :No such file or directory

### ISSUE THREAD

**Issue by dockies** [afzaalace/unsplash#5]
Can anyone help me to solve this problem?

**Comment by afzaalace** [comment]
Could you please add some more details, so that I can try to replicate the issue.

**Comment by dockies** [comment]
I just follow the instructions. After i install using npm install -g unsplash then i run the command it says no such file or director. Even when i  navigate to the folder where i want to save the images and using  unsplash -f the same error happens. I am a newbie so i rely only with the steps provided in the repo.

**Comment by afzaalace** [comment]
@dockies Are you on Windows ?

**Comment by dockies** [comment]
Sorry i forgot to mention im in linux

**Comment by mstnorris** [comment]
Same issue here.

Run Mac OS X 10.11, running `unsplash` to download images to current directory produces the error "env: node\r: No such file or directory".

**Comment by geradrum** [comment]
@mstnorris 
You need to convert the file in `your_modules_folder/unsplash/bin/unsplash` to Unix format.
You can install **dos2unix** (brew install) to do that and then running `sudo dos2unix the_unsplash_file` will solve your problem.
